---
title: "Maps"
author: "Frida Gomam"
date: 2015-07-23T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
library(tidyverse)
library(osmdata)
```

# R Markdown



```{r}
getbb("Phoenix United States")

streets <- getbb("Phoenix United States") %>% 
  opq() %>% 
  add_osm_feature(key = "highway",
                  value = c("motorway", "primary")) %>% 
  osmdata_sf()
```

# Including Plots

```{r}
small_streets <- getbb("Phoenix United States")%>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("secondary", "tertiary")) %>%
  osmdata_sf()

river <- getbb("Phoenix United States")%>%
  opq()%>%
  add_osm_feature(key = "waterway", value = "river") %>%
  osmdata_sf()
```


```{r}
ggplot() +
  geom_sf(data = streets$osm_lines,
          inherit.aes = FALSE,
          color = "#ffbe7f",
          size = .4,
          alpha = .8) +
  geom_sf(data = small_streets$osm_lines,
          inherit.aes = FALSE,
          color = "#ffbe7f",          
          size = .2,
          alpha = .6) +
  geom_sf(data = river$osm_lines,          
          inherit.aes = FALSE,          
          color = "#7fc0ff",          
          size = .2,          
          alpha = .5) +
  coord_sf(xlim = c(-112.32, -111.93), #change coords
           ylim = c(33.29, 33.92), #change coords
           expand = FALSE) +
  theme_void() +
  theme(plot.background = element_rect(fill = "#282828"))
```

